### ISSUE TITLE
Addon Managers get really confused by your Fork

### ISSUE THREAD

**Issue by ZINK-ZINK** [ItsJustMeChris/idTip-Community-Fork#16] opened 2022-10-31 15:34 UTC
I just noticed that the Curseforge App thinks your version of idTip is the old obsolete one. If you search in the App for idtip it shows both versions of the addon, but no matter what I did, even fully manually deleting idTip from Interface/WTF and installing it directly from the App, would get it to realize that I have your version installed. 

The best solution is for the original dev to give you full rights on curseforge, but if they're unresponsive then IMO the next best solution is for you to re-name or re-upload your version under a new Addon name. Even if you have to create an entire new Addon page to change the name I still think it's worth it in the long run; assuming you plan to continue updating it throughout DragonTown IMO you are the rightful owner of this new version. 

My new name suggestion is "TooltipIDs". It's self-descriptive enough to show up in a search.

**Comment by ItsJustMeChris** [comment] 2022-10-31 16:32
I'm not really noticing any issues on my end.. I'd have to reach out to curse and see what they advise, but as far as I can tell there don't seem to be any issues currently, the curse client is just buggy in general..

**Comment by ItsJustMeChris** [comment] 2022-11-02 16:38
Very weird, I'll open a ticket with overwolf and see if they recommend any changes on my end.

**Comment by Zorcan2112** [comment] 2022-11-02 18:36
Just to confirm, also occurring with CF app for me as well.  It's still updating correctly, and no issues.  But it does appear as Modified.

![Screenshot](https://user-images.githubusercontent.com/116864043/199573548-6b69a102-4aaf-4c5e-afea-442c151cfae4.jpg)

**Comment by JannesP** [comment] 2022-11-05 09:55
I'm fairly certain addon managers [(at least WowUp does)](https://github.com/WowUp/WowUp/blob/c5f85a2335692f9be4a07c664b6b417aeb7e0003/wowup-electron/src/app/services/toc/toc.service.ts#L30) tap into the toc file(s) and use the same ids that the [build script from the BigWigs team](https://github.com/BigWigsMods/packager#customizing-the-build) uses.

At least that's the only thing I've done for my unit frames and those get correctly picked up by both WowUp and CurseForge.

Despite that I still think the correct thing would be to rename the addon entirely, just to be on the safe side. Otherwise, we'll have a big mess if the old one gets updated at some point.

**Comment by ItsJustMeChris** [comment] 2022-11-06 17:36
@Zorcan2112 @ZINK-ZINK @Voxxel I've heard back from the Curse/Overwolf team and they aren't able to reproduce these issues either, they asked if there's any curse logs that can be provided, if you'd like to help you can send them to me and I'll forward them on. 

If you'd like to email them directly to curse you can reference the ticket number `145209`

<img width="468" alt="CleanShot 2022-11-06 at 11 35 16@2x" src="https://user-images.githubusercontent.com/21985209/200185931-648155d5-a878-4d8c-be66-e8baccac8d8f.png">

https://support.curseforge.com/en/support/tickets/new

You can email them to itsjustmechris@protonmail.com 

Thanks, hopefully we can narrow this down or at least eliminate some options before trying to brute force updates to attempt resolving.

**Comment by ItsJustMeChris** [comment] 2022-11-06 21:48
I am going to rename the addon directory however, since it does sound like something that could quite easily cause issues.

**Comment by Voxxel** [comment] 2022-11-07 00:32
I'd be grateful to share logs client but I don't know where can I find them.

**Comment by ZINK-ZINK** [comment] 2022-11-07 01:09
@ItsJustMeChris Pasting a pic of what I see on my end currently, iirc the same day I opened this ticket it changed from only showing the original idTip to showing your "modified community fork".

I'll fill out that curseforge ticket with the reference number, but I glanced through the curse-Log-zip and it includes some info personal enough to make me wary (like my WoW GUID, my drive directories+filenames, IP address etc) so I don't want to send those logs anywhere, especially Overwolf. 

I'm all for supporting addon devs, but I do not trust Overwolf whatsoever; I only use their site and addon app because they have a monopoly and I use hundreds of addons. 

If there's any other way I can help I'd be happy to though.
![Curse Bug 1](https://user-images.githubusercontent.com/96964163/200206879-b552b10c-6bd9-46a0-b91a-e95d2fda4be6.jpg)

**Comment by ZINK-ZINK** [comment] 2022-11-07 01:15
> I'd be grateful to share logs client but I don't know where can I find them.

This pic is how to create the Log, but be wary of Overwolf imo. You do you though, I could well just be overly paranoid.
![Curse Bug 2](https://user-images.githubusercontent.com/96964163/200207251-531157c0-7322-443c-8d66-5b9c6edd872e.jpg)

**Comment by kemayo** [comment] 2022-11-17 02:53
Just to chime in that this is a thing that still happens to me.

**Comment by ItsJustMeChris** [comment] 2022-11-17 03:47
I'm not able to recreate it in any degree, and neither was Curse themselves. They said the only thing that can really help is to contact them directly with curse client logs.

**Comment by klepp0906** [comment] 2022-11-23 18:34
> 's any curse logs that can be provided, if you'd like to help you can send them to me and I'll forward them on.

same issue here, hence my hunting this down on github

**Comment by ItsJustMeChris** [comment] 2022-12-03 17:19
I'm starting to see this bug sometimes with other addons.. Right clicking and pressing update seems to make it not an issue for me.. with these new observations I'm going to close this issue because I don't think it's isolated to just this addon and is a general curse issue..

**Closed by ItsJustMeChris** 2022-12-03 17:19 UTC
