### ISSUE TITLE
Mouseover container items with NPC behind the container frame

### ISSUE THREAD

**Issue by jjholleman** [ItsJustMeChris/idTip-Community-Fork#23] opened 2022-11-16 13:27 UTC
The NPC id gets duplicated in tooltips when hovering over (for example) container items with an NPC behind the frame. 

Open backback.
Align camera in such a way that the bag items are in such a way that there is an NPC behind the bag frame. 
Mouseover items.

The issue gets worse after playing longer, showing an unlimited amount of lines with NPC id.

![DCrLj7W](https://user-images.githubusercontent.com/6916881/202193175-029dc043-4c37-4b60-9c70-1da472717164.gif)

**Comment by ItsJustMeChris** [comment] 2022-11-16 16:02
I can't seem to reproduce it so I can't try to remedy it, but I'm not quite sure what I would ultimately be able to do in general since it's coming from blizzards `TooltipDataProcessor.AddTooltipPostCall` addition, perhaps there's some conflict with other addons or custom name plates or something.

I think that a solution can be to test that the `GetMouseFocus` is not the WorldFrame or a raid frame (GetMouseFocus().portrait)? 

I'll put it in and we can see.

**Comment by jjholleman** [comment] 2022-11-16 21:38
Well, it did fix the issue but it also disabled the NPC id from working on npc tooltips 😂

**Comment by cp1pro** [comment] 2022-11-17 22:20
ALL THE THINGS + Plater Nameplates + idTip Community Fork (11.0.22).
for case if u wanna reproduce that bug
![Screenshot_1330](https://user-images.githubusercontent.com/118368537/202571768-e46a6f4f-1a0c-4961-a327-156b2ec6e978.png)

**Comment by jjholleman** [comment] 2022-11-18 12:20
@ItsJustMeChris I've downgraded to version 11.0.22 to see if I could replicate the issue. I was able to narrow the issue down to Neatplates + idTip. Someone else also posted a comment here, but deleted it, with a combination of Plater + idTip, so it seems to be an issue in combination with nameplate addons.

**Comment by ItsJustMeChris** [comment] 2022-11-18 12:45
Yup seems like Plater is what's causing it, for some reason their frames are clipping through other frames, I think the code I had put in place had just a simple mistake and it seems to be working as I expected on my end, will fix and upload.

**Comment by cp1pro** [comment] 2022-11-18 13:25
> @ItsJustMeChris I've downgraded to version 11.0.22 to see if I could replicate the issue. I was able to narrow the issue down to Neatplates + idTip. Someone else also posted a comment here, but deleted it, with a combination of Plater + idTip, so it seems to be an issue in combination with nameplate addons.

i deleted the comment. because, this bug was with only one NPC in the whole dungeon. And I couldn't repeat it with another character. So far, this is a combination of unknown factors for me. let's see how it will be in the new version :D

**Comment by cp1pro** [comment] 2022-11-18 17:17
> > @ItsJustMeChris I've downgraded to version 11.0.22 to see if I could replicate the issue. I was able to narrow the issue down to Neatplates + idTip. Someone else also posted a comment here, but deleted it, with a combination of Plater + idTip, so it seems to be an issue in combination with nameplate addons.
> 
> i deleted the comment. because, this bug was with only one NPC in the whole dungeon. And I couldn't repeat it with another character. So far, this is a combination of unknown factors for me. let's see how it will be in the new version :D

is still happening. I found solutions but I don't know how it will affect the rest of the code.

core\shared.lua -> in function IDTipLib:addLine(tooltip, id, kind)   remove -> tooltip:Show()

Here is a video with a bug, there is a result with and without tooltip:Show().
[https://www.youtube.com/watch?v=2Vd4CMz1kkE](url)

**Comment by ItsJustMeChris** [comment] 2022-11-18 17:24
This looks like a different issue, and it's one that I can't replicate with Plater..

**Comment by ItsJustMeChris** [comment] 2022-11-18 17:25
@cp1pro do you have something making the nameplate stay forever?

**Comment by ItsJustMeChris** [comment] 2022-11-18 17:40
My last commit will validate that the unit token belongs to the mouseover or target which should resolver the 'false positives' caused by plater flooding the tooltip unit event, but just kinda grasping

**Comment by cp1pro** [comment] 2022-11-18 19:32
> @cp1pro do you have something making the nameplate stay forever?

I noticed that when there was a bug, the tooltip did not disappear, but hung until I hovered over another object. Of the addons, only AllTheThings should affect the tooltip, but everything is there by default. By the way, the bug was only when three addons are enabled.

**Comment by cp1pro** [comment] 2022-11-18 20:24
Seems like the last fix works. At least that mob stopped bugging.

**Comment by jjholleman** [comment] 2022-11-18 22:17
It was showing multiple NPC ids when hovering over a player's character model, during a M+ key. Only bugged for one specific player and it stopped when the M+ dungeon was finished. 
I see you made a new release, I'll play some more tomorrow and let you know if your fix worked ;-)

**Closed** 2022-12-03 17:19 UTC
